export const PAGE = {
    VIEW: "VIEW",
    ADD: "ADD",
    EDIT: "EDIT",
    FILTER: "FILTER"
}

export const SORT = {
    BARCODEUP: "BARCODEUP",
    BARCODEDOWN: "BARCODEDOWN",
    TITLEUP: "TITLEUP",
    TITLEDOWN: "TITLEDOWN",
    CATEGORYUP: "CATEGORYUP",
    CATEGORYDOWN: "CATEGORYDOWN",
    COSTUP: "COSTUP",
    COSTDOWN: "COSTDOWN",
    PRICEUP: "PRICEUP",
    PRICEDOWN: "PRICEDOWN",
    QUANTITYUP: "QUANTITYUP",
    QUANTITYDOWN: "QUANTITYDOWN",
    NONE: "NONE"
}